### ISSUE TITLE
Save image via Chrome browser without extension

### ISSUE THREAD

**Issue by SiavaRu** [satanasov/phpbbgallery#114] opened 2016-05-22 16:46 UTC
Hi, Stanislav!
One not a serious bug.

When I save photo via Chrome browser (right click -> save image) file saves without extension.
In Firefox and IE all ok.

**Comment by satanasov** [comment] 2016-05-22 21:30
Duplicate of #112

**Closed by satanasov** 2016-05-22 21:30 UTC
